config/routes.rb
Rails.application.routes.draw do
  get 'auth0/callback'

  get 'auth0/failure'
    
  resources :upvotes
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	scope "/admin" do
	resources :users
  end
    resources :complains do
        collection do
            get :myComplains
            get :report
            post :addvote
            get :close
        end
    end  
    resources :usertypes
  resources :wards
  resources :zones
  resources :feedbacks
 
  root to: "users#index"

 
 post "admin/users/show"
 post "complains/addvote"
    
  
 post "admin/users/show"
 post "complains/addvote"
    

  post "admin/users/show"
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  devise_scope :user do
	get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit'  => 'devise/registrations#edit'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/upvote.rb
class Upvote < ApplicationRecord
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_upvote, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit,:report,:update]  
  # GET /upvotes
  # GET /upvotes.json
  def index
    @upvotes = Upvote.all
  end

  # GET /upvotes/1
  # GET /upvotes/1.json
  def show
  end

  # GET /upvotes/new
  def new
    @upvote = Upvote.new
  end

  # GET /upvotes/1/edit
  def edit
  end

  # POST /upvotes
  # POST /upvotes.json
  def create
    @upvote = Upvote.new(upvote_params)

    respond_to do |format|
      if @upvote.save
        format.html { redirect_to @upvote, notice: 'Upvote was successfully created.' }
        format.json { render :show, status: :created, location: @upvote }
      else
        format.html { render :new }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upvotes/1
  # PATCH/PUT /upvotes/1.json
  def update
    respond_to do |format|
      if @upvote.update(upvote_params)
        format.html { redirect_to @upvote, notice: 'Upvote was successfully updated.' }
        format.json { render :show, status: :ok, location: @upvote }
      else
        format.html { render :edit }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upvotes/1
  # DELETE /upvotes/1.json
  def destroy
    @upvote.destroy
    respond_to do |format|
      format.html { redirect_to upvotes_url, notice: 'Upvote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upvote
      @upvote = Upvote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upvote_params
      params.require(:upvote).permit(:has_many, :has_many)
    end

     def check_user
    if current_user.usertypeid==2
      flash[:alert]='You are not authorized to access this page.'
      redirect_to root_path
    end
   end
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/upvotes/_form.html.erb
<%= simple_form_for(@upvote) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :has_many %>
    <%= f.input :has_many %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/upvotes/edit.html.erb
<h1>Editing Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Show', @upvote %> |
<%= link_to 'Back', upvotes_path %>

app/views/upvotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Upvotes</h1>

<table>
  <thead>
    <tr>
      <th>Has many</th>
      <th>Has many</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upvotes.each do |upvote| %>
      <tr>
        <td><%= upvote.has_many %></td>
        <td><%= upvote.has_many %></td>
        <td><%= link_to 'Show', upvote %></td>
        <td><%= link_to 'Edit', edit_upvote_path(upvote) %></td>
        <td><%= link_to 'Destroy', upvote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upvote', new_upvote_path %>

app/views/upvotes/new.html.erb
<h1>New Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Back', upvotes_path %>

app/views/upvotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Has many:</strong>
  <%= @upvote.has_many %>
</p>

<p>
  <strong>Has many:</strong>
  <%= @upvote.has_many %>
</p>

<%= link_to 'Edit', edit_upvote_path(@upvote) %> |
<%= link_to 'Back', upvotes_path %>