config/routes.rb
Rails.application.routes.draw do
  get 'auth0/callback'

  get 'auth0/failure'
    
  resources :upvotes
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	scope "/admin" do
	resources :users
  end
    resources :complains do
        collection do
            get :myComplains
            get :report
            post :addvote
            get :close
        end
    end  
    resources :usertypes
  resources :wards
  resources :zones
  resources :feedbacks
 
  root to: "users#index"

 
 post "admin/users/show"
 post "complains/addvote"
    
  
 post "admin/users/show"
 post "complains/addvote"
    

  post "admin/users/show"
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  devise_scope :user do
	get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit'  => 'devise/registrations#edit'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/usertypes_controller.rb
class UsertypesController < ApplicationController
  before_action :set_usertype, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  # GET /usertypes
  # GET /usertypes.json
  def index
    @usertypes = Usertype.all
  end

  # GET /usertypes/1
  # GET /usertypes/1.json
  def show
  end

  # GET /usertypes/new
  def new
    @usertype = Usertype.new
  end

  # GET /usertypes/1/edit
  def edit
  end

  # POST /usertypes
  # POST /usertypes.json
  def create
    @usertype = Usertype.new(usertype_params)

    respond_to do |format|
      if @usertype.save
        format.html { redirect_to @usertype, notice: 'Usertype was successfully created.' }
        format.json { render :show, status: :created, location: @usertype }
      else
        format.html { render :new }
        format.json { render json: @usertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usertypes/1
  # PATCH/PUT /usertypes/1.json
  def update
    respond_to do |format|
      if @usertype.update(usertype_params)
        format.html { redirect_to @usertype, notice: 'Usertype was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertype }
      else
        format.html { render :edit }
        format.json { render json: @usertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertypes/1
  # DELETE /usertypes/1.json
  def destroy
    @usertype.destroy
    respond_to do |format|
      format.html { redirect_to usertypes_url, notice: 'Usertype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usertype
      @usertype = Usertype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usertype_params
      params.require(:usertype).permit(:usertype)
    end

     def check_user
    if current_user.usertypeid==2
      flash[:alert]='You are not authorized to access this page.'
      redirect_to root_path
    end
   end
end

app/helpers/usertypes_helper.rb
module UsertypesHelper
end

app/views/usertypes/_form.html.erb
<%= form_for(usertype) do |f| %>
  <% if usertype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usertype.errors.count, "error") %> prohibited this usertype from being saved:</h2>

      <ul>
      <% usertype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usertype %>
    <%= f.text_field :usertype %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertypes/edit.html.erb
<h1>Editing Usertype</h1>

<%= render 'form', usertype: @usertype %>

<%= link_to 'Show', @usertype %> |
<%= link_to 'Back', usertypes_path %>

app/views/usertypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usertypes</h1>

<table>
  <thead>
    <tr>
      <th>Usertype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usertypes.each do |usertype| %>
      <tr>
        <td><%= usertype.usertype %></td>
        <td><%= link_to 'Show', usertype %></td>
        <td><%= link_to 'Edit', edit_usertype_path(usertype) %></td>
        <td><%= link_to 'Destroy', usertype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usertype', new_usertype_path %>

app/views/usertypes/new.html.erb
<h1>New Usertype</h1>

<%= render 'form', usertype: @usertype %>

<%= link_to 'Back', usertypes_path %>

app/views/usertypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usertype:</strong>
  <%= @usertype.usertype %>
</p>

<%= link_to 'Edit', edit_usertype_path(@usertype) %> |
<%= link_to 'Back', usertypes_path %>