config/routes.rb
Rails.application.routes.draw do
  get 'auth0/callback'

  get 'auth0/failure'
    
  resources :upvotes
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	scope "/admin" do
	resources :users
  end
    resources :complains do
        collection do
            get :myComplains
            get :report
            post :addvote
            get :close
        end
    end  
    resources :usertypes
  resources :wards
  resources :zones
  resources :feedbacks
 
  root to: "users#index"

 
 post "admin/users/show"
 post "complains/addvote"
    
  
 post "admin/users/show"
 post "complains/addvote"
    

  post "admin/users/show"
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  devise_scope :user do
	get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit'  => 'devise/registrations#edit'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/zone.rb
class Zone < ApplicationRecord
	has_many :wards
	validates :zonename, :admin_username, presence: true
	validates :zonename, :admin_username, uniqueness: true
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]
  before_action :check_user

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:zonename, :admin_username)
    end

     def check_user
    if current_user.usertypeid==2
      flash[:alert]='You are not authorized to access this page.'
      redirect_to root_path
    end
   end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for(zone) do |f| %>
  <% if zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zonename %>
    <%= f.text_field :zonename %>
  </div>

  <div class="field">
    <%= f.label :admin_username %>
    <%= f.text_field :admin_username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zones</h1>

<table>
  <thead>
    <tr>
      <th>Zonename</th>
      <th>Admin username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.zonename %></td>
        <td><%= zone.admin_username %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zonename:</strong>
  <%= @zone.zonename %>
</p>

<p>
  <strong>Admin username:</strong>
  <%= @zone.admin_username %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>