config/routes.rb
Rails.application.routes.draw do
  get 'auth0/callback'

  get 'auth0/failure'
    
  resources :upvotes
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	scope "/admin" do
	resources :users
  end
    resources :complains do
        collection do
            get :myComplains
            get :report
            post :addvote
            get :close
        end
    end  
    resources :usertypes
  resources :wards
  resources :zones
  resources :feedbacks
 
  root to: "users#index"

 
 post "admin/users/show"
 post "complains/addvote"
    
  
 post "admin/users/show"
 post "complains/addvote"
    

  post "admin/users/show"
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  devise_scope :user do
	get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit'  => 'devise/registrations#edit'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ward.rb
class Ward < ApplicationRecord
	belongs_to :zone
	validates :wardno, :wardname, presence: true
	validates :wardno, uniqueness: true
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to @ward, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:wardno, :wardname, :zoneid)
    end

     def check_user
    if current_user.usertypeid==2
      flash[:alert]='You are not authorized to access this page.'
      redirect_to root_path
    end
   end
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_for(ward) do |f| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
      <% ward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wardno %>
    <%= f.number_field :wardno %>
  </div>

  <div class="field">
    <%= f.label :wardname %>
    <%= f.text_field :wardname %>
  </div>

  <div class="field">
    <%= f.label :zoneid %>
    <%= f.number_field :zoneid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Show', @ward %> |
<%= link_to 'Back', wards_path %>

app/views/wards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wards</h1>

<table>
  <thead>
    <tr>
      <th>Wardno</th>
      <th>Wardname</th>
      <th>Zoneid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wards.each do |ward| %>
      <tr>
        <td><%= ward.wardno %></td>
        <td><%= ward.wardname %></td>
        <td><%= ward.zoneid %></td>
        <td><%= link_to 'Show', ward %></td>
        <td><%= link_to 'Edit', edit_ward_path(ward) %></td>
        <td><%= link_to 'Destroy', ward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ward', new_ward_path %>

app/views/wards/new.html.erb
<h1>New Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Back', wards_path %>

app/views/wards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wardno:</strong>
  <%= @ward.wardno %>
</p>

<p>
  <strong>Wardname:</strong>
  <%= @ward.wardname %>
</p>

<p>
  <strong>Zoneid:</strong>
  <%= @ward.zoneid %>
</p>

<%= link_to 'Edit', edit_ward_path(@ward) %> |
<%= link_to 'Back', wards_path %>